### ISSUE TITLE
[Feat] 프로필 영역 디자인 추가

### ISSUE THREAD

**Issue by Mule129** [Team-EverFlow/CheckAndTalk_FrontEnd#2]
## 필요한 기능
- 프사 선택기능 디자인
- 닉네임 등록/수정 기능 디자인
- 상태메시지 등록/수정 기능 디자인
- 레벨 표시

## 해야 할 일 
- [x] 프사 수정 선택 시 뜨는 팝업창 디자인(피그마)
- [x] 프로필 영역 레이아웃 구현
- [x] 프로필 내 프사, 닉네임, 상태메시지 등록/수정기능 구현

## 추가 컨텍스트
- 프사가 색만 다르고 디자인이 똑같으니 그냥 색만 뜨면서 고르게 하거나... 미리보기로 그냥 모든 이미지 띄우거나.. 어떤 방식이 나을것같나요?
- 레벨을 한개의 할일을 마칠때마다 1pt씩 늘릴지, 아니면 누적 증가치를 줄지, 사용자 레벨이 오를수록 포인트 얻기 힘들어지게 할지.... (백앤드 쪽에 가깝긴 한데 어떤게 좋아보이나요?)

**Comment by HanGyeongjun** [comment]
추가 컨텍스트 관련 의견 남깁니다!
1. 프로필 이미지 같은 경우 처음에는 랜덤 이미지로 배정 후, 추후 사용자가 원하면 이미지를 수정하는 방식이 최초 가입 시 사용자가 해야 하는 태스크가 줄어 편리할 것 같습니다. (절대 귀차니즘 때문이 아닙니다..ㅎㅎㅎ)
    - 만약 최초 가입 시 설정 단계가 추가된다면, 닉네임도 함께 설정할 수 있어야 할 것 같습니다.
3. 레벨 시스템의 정책은 저희가 논의 후 적용하면 될 것 같습니다.
    - 개인적으로 할 일 1개/5개/10개/25개/50개/.. 등으로 올라가면 해당 구간에 맞는 레벨을 적용해주는 방식이 가장 깔끔하지 않을까 생각합니다.
    - 화면에 표시되는 게이지에는 현재 레벨에서 얼마나 진행되었는지(다음 레벨업까지 얼마나 남았는지)를 표시하는 것은 어떨까요..?

**Comment by xqqldir** [comment]
- 색이 적용 된 다섯 개의 이미지를 띄워주고 사용자가 선택할 수 있도록 하는 것이 좋을 것 같습니다. 
- 만약 색상만 뜨게 하고싶다면 프로필 사진을 가리지 않게 색상 선택 바를 띄운 후 선택한 색상으로 프로필 이미지가 바뀌면서 미리보기 느낌으로 볼 수 있도록 해도 괜찮을 것 같습니다. 
- 할일 1개 완료 == 1 point 로 설정 한 후 1 level 은 1pt, 2 level 은 3pt, 3 level은 9pt 이런식으로 배수로 증가시키는거 어떤가요?
그리고 얼마나 진행되었는지 표시하는 것은 좋은데 어렵거나 힘들거나 귀찮다면 굳이 구현할 필요는 없을 것 같습니다.

**Comment by Mule129** [comment]
두분 모두 의견 감사합니다! 의견을 종합하자면,
1. 가입시엔 최대한 태스크를 줄여 랜덤 닉네임, 프로필로 두고 이후 수정할 때 색이 적용 된 다섯개의 이미지를 띄워 사용자가 선택할 수 있도록 하는게 좋을 것 같습니다
2. 레벨의 경우 배수 증가로 할 경우, 후반으로 갈수록 레벨을 올리기 힘들 것 같아 한 레벨의 2배수 포인트를 띄우는게 좋을 것 같습니다(더 좋은 의견 있으면 부탁드립니다)
3. 레벨 뒷부분에 진행도(게이지) 추가하겠습니다
